In [1]:
import numpy as np

In [2]:
import pandas as pd

In [3]:
test =pd.read_csv('dados/UNSW_NB15_testing-set.csv')
train = pd.read_csv('dados/UNSW_NB15_training-set.csv')

In [6]:
previsores_train = train.iloc[:,train.columns.isin(('sload','dload',
                                                   'spkts','dpkts','swin','dwin','smean','dmean',
'sjit','djit','sinpkt','dinpkt','tcprtt','synack','ackdat','ct_srv_src','ct_srv_dst','ct_dst_ltm',
 'ct_src_ltm','ct_src_dport_ltm','ct_dst_sport_ltm','ct_dst_src_ltm')) ].values

In [7]:
previsores_train

array([[2.00000000e+00, 0.00000000e+00, 1.80363632e+08, ...,
        2.00000000e+00, 1.00000000e+00, 2.00000000e+00],
       [2.00000000e+00, 0.00000000e+00, 8.81000000e+08, ...,
        2.00000000e+00, 1.00000000e+00, 2.00000000e+00],
       [2.00000000e+00, 0.00000000e+00, 8.54400000e+08, ...,
        3.00000000e+00, 1.00000000e+00, 3.00000000e+00],
       ...,
       [1.00000000e+00, 0.00000000e+00, 0.00000000e+00, ...,
        1.00000000e+00, 1.00000000e+00, 1.00000000e+00],
       [1.00000000e+00, 0.00000000e+00, 0.00000000e+00, ...,
        1.00000000e+00, 1.00000000e+00, 1.00000000e+00],
       [2.00000000e+00, 0.00000000e+00, 4.62222200e+07, ...,
        1.00000000e+00, 1.00000000e+00, 1.00000000e+00]])

In [8]:
classe_train = train.iloc[:, -1].values

In [9]:
classe_train

array([0, 0, 0, ..., 0, 0, 0])

In [10]:
previsores_train

array([[2.00000000e+00, 0.00000000e+00, 1.80363632e+08, ...,
        2.00000000e+00, 1.00000000e+00, 2.00000000e+00],
       [2.00000000e+00, 0.00000000e+00, 8.81000000e+08, ...,
        2.00000000e+00, 1.00000000e+00, 2.00000000e+00],
       [2.00000000e+00, 0.00000000e+00, 8.54400000e+08, ...,
        3.00000000e+00, 1.00000000e+00, 3.00000000e+00],
       ...,
       [1.00000000e+00, 0.00000000e+00, 0.00000000e+00, ...,
        1.00000000e+00, 1.00000000e+00, 1.00000000e+00],
       [1.00000000e+00, 0.00000000e+00, 0.00000000e+00, ...,
        1.00000000e+00, 1.00000000e+00, 1.00000000e+00],
       [2.00000000e+00, 0.00000000e+00, 4.62222200e+07, ...,
        1.00000000e+00, 1.00000000e+00, 1.00000000e+00]])

In [11]:
classe_test = test.iloc[:, -1].values

In [12]:
classe_test

array([0, 0, 0, ..., 1, 1, 1])

In [13]:
train.columns

Index(['id', 'dur', 'proto', 'service', 'state', 'spkts', 'dpkts', 'sbytes',
       'dbytes', 'rate', 'sttl', 'dttl', 'sload', 'dload', 'sloss', 'dloss',
       'sinpkt', 'dinpkt', 'sjit', 'djit', 'swin', 'stcpb', 'dtcpb', 'dwin',
       'tcprtt', 'synack', 'ackdat', 'smean', 'dmean', 'trans_depth',
       'response_body_len', 'ct_srv_src', 'ct_state_ttl', 'ct_dst_ltm',
       'ct_src_dport_ltm', 'ct_dst_sport_ltm', 'ct_dst_src_ltm',
       'is_ftp_login', 'ct_ftp_cmd', 'ct_flw_http_mthd', 'ct_src_ltm',
       'ct_srv_dst', 'is_sm_ips_ports', 'attack_cat', 'label'],
      dtype='object')

In [14]:
test.columns

Index(['id', 'dur', 'proto', 'service', 'state', 'spkts', 'dpkts', 'sbytes',
       'dbytes', 'rate', 'sttl', 'dttl', 'sload', 'dload', 'sloss', 'dloss',
       'sinpkt', 'dinpkt', 'sjit', 'djit', 'swin', 'stcpb', 'dtcpb', 'dwin',
       'tcprtt', 'synack', 'ackdat', 'smean', 'dmean', 'trans_depth',
       'response_body_len', 'ct_srv_src', 'ct_state_ttl', 'ct_dst_ltm',
       'ct_src_dport_ltm', 'ct_dst_sport_ltm', 'ct_dst_src_ltm',
       'is_ftp_login', 'ct_ftp_cmd', 'ct_flw_http_mthd', 'ct_src_ltm',
       'ct_srv_dst', 'is_sm_ips_ports', 'attack_cat', 'label'],
      dtype='object')

In [17]:
previsores_test = test.iloc[:,test.columns.isin(('sload','dload',
                                                   'spkts','dpkts','swin','dwin','smean','dmean',
'sjit','djit','sinpkt','dinpkt','tcprtt','synack','ackdat','ct_srv_src','ct_srv_dst','ct_dst_ltm',
 'ct_src_ltm','ct_src_dport_ltm','ct_dst_sport_ltm','ct_dst_src_ltm')) ].values

In [18]:
previsores_test

array([[6.00000000e+00, 4.00000000e+00, 1.41589424e+04, ...,
        1.00000000e+00, 1.00000000e+00, 1.00000000e+00],
       [1.40000000e+01, 3.80000000e+01, 8.39511231e+03, ...,
        2.00000000e+00, 1.00000000e+00, 6.00000000e+00],
       [8.00000000e+00, 1.60000000e+01, 1.57227185e+03, ...,
        3.00000000e+00, 2.00000000e+00, 6.00000000e+00],
       ...,
       [2.00000000e+00, 0.00000000e+00, 5.06666640e+07, ...,
        1.30000000e+01, 3.00000000e+00, 1.20000000e+01],
       [2.00000000e+00, 0.00000000e+00, 5.06666640e+07, ...,
        3.00000000e+01, 3.00000000e+01, 3.00000000e+01],
       [2.00000000e+00, 0.00000000e+00, 5.06666640e+07, ...,
        3.00000000e+01, 3.00000000e+01, 3.00000000e+01]])

In [19]:
X_train2,y_train2 = previsores_train,classe_train

X_test2,y_test2 = previsores_test,classe_test

In [21]:
import keras

Using TensorFlow backend.


In [22]:
from keras.models import Sequential

In [23]:
from keras.layers import Dense

In [24]:
classificador_rede_neural = Sequential()

In [25]:
features = previsores_train.shape[1] #num de atributos previsores

In [26]:
print('numero de features', features)

numero de features 22


In [27]:
camadas_ocultas = round((features + 1)/2 )

In [28]:
print(camadas_ocultas)

12


In [29]:
classificador_rede_neural.add(Dense(units=camadas_ocultas, activation='relu',input_dim = features ))#primeira camada

In [30]:
classificador_rede_neural.add(Dense(units=camadas_ocultas, activation='relu' ))#segunda camada

In [31]:
classificador_rede_neural.add(Dense(units=1, activation='sigmoid' ))#camada de saída. a saída é binária, logo units=1

In [32]:
classificador_rede_neural.compile(optimizer='adam',loss='binary_crossentropy',metrics=['accuracy'])

In [33]:
X_train2.shape

(82332, 22)

In [34]:
y_train2.shape

(82332,)

In [35]:
classificador_rede_neural.fit(X_train2,y_train2)#é treino: trocar

Epoch 1/1
82332/82332 [==============================] - 3s 42us/step - loss: 9.0581 - acc: 0.4372
